config/routes.rb
Karma::Application.routes.draw do

  root :to => 'main#home'

  resources :users, :only => [:update]
  match "/add_your_email" => "users#add_email", :as => :add_email

  resources :needs, :only => [:new, :create] do
    get 'thanks', :on => :collection
  end

  match "/auth/:provider/callback" => "sessions#create"
  match "/sign_out" => "sessions#destroy", :as => :sign_out
  match "/auth/failure" => "sessions#failure", :as => :authentication_failure

  match "/post" => "incoming_mail#post_event"

  resources :sessions, :only => [:create]

  namespace :admin do
    resources :emails
    resources :users
    resources :needs
  end

end

app/models/need.rb
class Need < ActiveRecord::Base
  belongs_to :user
  belongs_to :mentor, :class_name => "User"
  has_many :emails

  validates_presence_of :user_id
  validates_presence_of :body
end

app/controllers/admin/needs_controller.rb
class Admin::NeedsController < Admin::BaseController

  before_filter :authenticate, :except => :index

  def index
    @needs = Need.all
  end

  def show
    @need = Need.find(params[:id])
  end

  def new
    @need = Need.new
    @need.user_id = session[:user_id]
  end

  def edit
    @need = Need.find(params[:id])
  end

  def create
    @need = Need.new(params[:need])
    @need.user_id = session[:user_id]

    if @need.save
      redirect_to admin_need_path(@need), notice: 'Need was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @need = Need.find(params[:id])

    if @need.update_attributes(params[:need])
      redirect_to admin_need_path(@need), notice: 'Need was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @need = Need.find(params[:id])
    @need.destroy

    redirect_to admin_needs_url
  end
end

app/controllers/needs_controller.rb
class NeedsController < ApplicationController

  before_filter :authenticate, :sign_up_next_step

  def new
    @user = current_user

    max_needs.times do
      need = @user.needs.build
      need.user_id = @user.id
    end

  end

  def create
    success = true

    @user = current_user

    max_needs.times do
      need = @user.needs.build(params[:need])
      need.user_id = @user.id

      if !need.save
        success = false
      end
    end

    if (success)
      redirect_to thanks_needs_path, notice: 'Needs saved.'
    else
      render action: "new"
    end

  end

  def thanks
  end

end

app/views/needs/_form.haml
= form_for(@user) do |user_form|
  = render :partial => "error_messages", :locals => { :resource => @user }
  = user_form.fields_for :needs do |needs_form|
    = needs_form.label :body, "Need"
    = needs_form.text_area :body, :rows => 3
    -# = needs_form.check_box :_destroy
    -# = needs_form.label :_destroy, "Remove Need"
    %p
  .actions
    = user_form.submit 'Submit', :class => 'red_button'

app/views/needs/index.haml
- title "Needs for " + current_user.name

#needs_index
  %table
    %tr
      %th Body
    - @needs.each do |need|
      %tr
        %td= need.body
  %p
    = link_to 'New Need', new_need_path, :class => 'green_button'

app/views/needs/new.haml
- title "Karma - " + current_user.name

%section#new_need_container
  %blockquote
    %p Describe your biggest challenge in your life right now.  Examples:
    %p - I'm in-between jobs right now and could use help finding a new opportunity.
    %p - I am looking to hire a new employee at my company.
    %p - I'd like a good recommendation for a lawyer in the San Francisco area
    %p - I'm looking to start a new hobby and would love to have friends who can try it with me
    %p - I need some feedback on my business plan
    %p - I'm looking for customers for my business
    %p
    %p Try to focus on what you can't find using a quick google search, but that you need a real person to help you solve.
    %p Be as specific as possible.  You'll have the opportunity to share this with your friends and others to help you.
  = render 'form'

app/views/needs/thanks.haml
- title "Thanks!"
- font "http://fonts.googleapis.com/css?family=Permanent+Marker"

#needs_thanks
  %h1 All Done!
  %p You'll receive an email when someone offers to help you.
  %p You'll also receive an email if your friends need help with anything!
  %p There's nothing else to do, but you can push this button if you'd like:
  .center
    .blue_button Patience