config/routes.rb
Karma::Application.routes.draw do

  root :to => 'main#home'

  resources :users, :only => [:update]
  match "/add_your_email" => "users#add_email", :as => :add_email

  resources :needs, :only => [:new, :create] do
    get 'thanks', :on => :collection
  end

  match "/auth/:provider/callback" => "sessions#create"
  match "/sign_out" => "sessions#destroy", :as => :sign_out
  match "/auth/failure" => "sessions#failure", :as => :authentication_failure

  match "/post" => "incoming_mail#post_event"

  resources :sessions, :only => [:create]

  namespace :admin do
    resources :emails
    resources :users
    resources :needs
  end

end

app/models/need.rb
class Need < ActiveRecord::Base
  belongs_to :user
  belongs_to :mentor, :class_name => "User"
  has_many :emails

  validates_presence_of :user_id
  validates_presence_of :body
end

app/controllers/admin/needs_controller.rb
class Admin::NeedsController < Admin::BaseController

  before_filter :authenticate, :except => :index

  def index
    @needs = Need.all
  end

  def show
    @need = Need.find(params[:id])
  end

  def new
    @need = Need.new
    @need.user_id = session[:user_id]
  end

  def edit
    @need = Need.find(params[:id])
  end

  def create
    @need = Need.new(params[:need])
    @need.user_id = session[:user_id]

    if @need.save
      redirect_to admin_need_path(@need), notice: 'Need was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @need = Need.find(params[:id])

    if @need.update_attributes(params[:need])
      redirect_to admin_need_path(@need), notice: 'Need was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @need = Need.find(params[:id])
    @need.destroy

    redirect_to admin_needs_url
  end
end

app/controllers/needs_controller.rb
class NeedsController < ApplicationController

  before_filter :authenticate, :sign_up_next_step

  def new
    @user = current_user

    max_needs.times do
      need = @user.needs.build
      need.user_id = @user.id
    end

  end

  def create
    success = true

    @user = current_user

    max_needs.times do
      need = @user.needs.build(params[:need])
      need.user_id = @user.id

      if !need.save
        success = false
      end
    end

    if (success)
      redirect_to thanks_needs_path, notice: 'Needs saved.'
    else
      render action: "new"
    end

  end

  def thanks
  end

end

app/views/admin/needs/_form.haml
= form_for [:admin, @need] do |f|
  = render :partial => "error_messages", :locals => { :resource => @need }
  .field
    = f.label :user_id
    = collection_select :need, :user_id, User.all, :id, :name, {:include_blank => true}
  .field
    = f.label :body
    %br/
    = f.text_field :body
  -# .field
  -#  = f.label :mentor
  -#  = collection_select :need, :mentor_id, User.all, :id, :name, {:include_blank => true}
  -#  %br/
  .actions
    = f.submit

app/views/admin/needs/edit.haml
- title "Edit Need for " + @need.user.try(:name) + " - Admin"
%h1 Administrative View: Editing need
= render 'form'
= link_to 'show', admin_need_path(@need)
|
= link_to 'Index', admin_needs_path

app/views/admin/needs/index.haml
- title "Needs Index - Admin"

%h1 Administrative View: Listing needs
%table
  %tr
    %th UserID
    %th Email
    %th Body
    %th Mentor
    %th
    %th
    %th
  - @needs.each do |need|
    %tr
      %td= need.user_id
      %td= need.user.try(:email)
      %td= need.body
      %td= need.mentor.try(:name)
      %td= link_to 'Show', admin_need_path(need)
      %td= link_to 'Edit', edit_admin_need_path(need)
      %td= link_to 'Destroy', admin_need_path(need), confirm: 'Are you sure?', method: :delete
= link_to 'New Need', new_admin_need_path

app/views/admin/needs/new.haml
- title "New Need - Admin"
%h1 Administrative View: New need
= render 'form'
= link_to 'Back', admin_needs_path

app/views/admin/needs/show.haml
- title "Need for " + @need.user.try(:name) + " - Admin"

%p#notice= notice
Administrative View: Showing Need
%p
  %b UserID:
  = @need.user_id
%p
  %b Email:
  = @need.user.try(:email)
%p
  %b Body:
  = @need.body
%p
  %b Mentor:
  = @need.mentor.try(:name)

= link_to 'Edit', edit_admin_need_path(@need)
|
= link_to 'Back', admin_needs_path