config/routes.rb
Karma::Application.routes.draw do

  root :to => 'main#home'

  resources :users, :only => [:update]
  match "/add_your_email" => "users#add_email", :as => :add_email

  resources :needs, :only => [:new, :create] do
    get 'thanks', :on => :collection
  end

  match "/auth/:provider/callback" => "sessions#create"
  match "/sign_out" => "sessions#destroy", :as => :sign_out
  match "/auth/failure" => "sessions#failure", :as => :authentication_failure

  match "/post" => "incoming_mail#post_event"

  resources :sessions, :only => [:create]

  namespace :admin do
    resources :emails
    resources :users
    resources :needs
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :emails

  # Since the user has_many needs, so we need to explicitly define the foreign key relationship
  has_many :helped_needs, :class_name => "Need", :foreign_key => "mentor_id"

  # For the view to work, a "needs_attributes=" writer method is required for fields_for to correctly identify :needs as a collection, and the correct indices to be set in the form markup.
  # 2 approaches:
  # A) Use accepts_nested_attributes_for, which defines an attributes writer method for you (NOTE: The ":body" here is just an example and should be customized)
	# B) Define a writer method manually
  has_many :needs
  accepts_nested_attributes_for :needs, :allow_destroy => true, :reject_if => lambda { |a| a[:body].blank? }
#  def needs_attributes=(attributes)
#    ...Write code here to process the attributes hash...
#  end

  validates_presence_of :name
  validates_uniqueness_of :email, :case_sensitive => false
  #validates_format_of :address, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,}$/i TODO: Validate the email when there is an email but not when creating from omniauth.

	def self.create_with_omniauth(auth)
	  create! do |user|
	    user.provider = auth["provider"]
	    user.uid = auth["uid"]
	    user.name = auth["info"]["name"]
      user.email = auth["info"]["email"]
      user.token = auth["credentials"]["token"]
      user.secret = auth["credentials"]["secret"]
	  end
  end

  def first_name
    name.sub(/ .*/, '') rescue ''
  end

  def has_needs?
    !needs.blank?
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  before_filter :authenticate

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
    @user.user_id = session[:user_id]
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    @user.user_id = session[:user_id]
    if @user.save
      redirect_to admin_user_path(@user), notice: 'User was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to admin_user_path(@user), notice: 'User was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate
  before_filter :sign_up_next_step, :except => [:add_email, :update]

  def add_email
    @user = current_user
  end

  # this update method applies to the add_email and new_need form
  def update
    @user = current_user

    # If the PUT parameters validate into usable fields for "user"...
    if (@user && @user.update_attributes(params[:user]))
      redirect_to root_path, :notice => "Success! w00t w00t!"
    # If there's an error, then it must have come from the add_email or new_need form since that actually has fields.
    else
      # TODO: This is a hack.. need to probably break this controller out into multiple controllers to solve this with intelligent errors.
      redirect_to :back, :notice => "Form has errors - please try again."
    end
  end

end

app/views/admin/users/_form.haml
= form_for [:admin, @user] do |f|
  = render :partial => "error_messages", :locals => { :resource => @user }
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.text_field :email
  .actions
    = f.submit 'Save', :class => 'blue_button'

app/views/admin/users/edit.haml
- title "Edit " + @user.name + " - Admin"

%h1 Editing users

= render 'form'

= link_to 'Show', admin_user_path(@user)
\|
= link_to 'Back', admin_users_path

app/views/admin/users/index.haml
- title "Users Index - Admin"

%h1 Listing Users
%table
  %tr
    %th User
    %th Email
    %th
  - @users.each do |user|
    %tr
      %td
        = link_to user.try(:name), admin_user_path(user)
      %td
        = user.email

      %td= link_to 'Destroy', admin_user_path(user), :confirm => 'Are you sure?', :method => :delete

app/views/admin/users/show.haml
- title @user.name + " - Admin"

%p
  %b Name:
  = @user.name

%p
  %b Email:
  = @user.email

= link_to 'Edit', edit_admin_user_path(@user)
\|
= link_to 'Back', admin_users_path